[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
check-manifest = ">=0.25"
pre-commit = "*"
pytest-invenio = "*"

[packages]
invenio-app-rdm = {extras = ["postgresql", "opensearch2"], version = "~=11.0.0"}
ic-data-repo = {editable="True", path="./site"}
invenio-saml = {}

uwsgi = ">=2.0"
uwsgitop = ">=0.11"
uwsgi-tools = ">=1.1.1"
# Pin sqlalchemy-continuum version for compatibility with pytest-invenio.
# sqlalchemy-continuum==1.4 implicitly assumes sqlalchemy>=2 but does not specify this
# constraint. The database fixture of the version of pytest-invenio in use uses an api
# deprecated in sqlalchemy==2. sqlalchemy-continuum==1.4 assumes use of the
# sqlalchemy==2 version of the api which causes an issue.
# Reported via https://github.com/kvesteri/sqlalchemy-continuum/issues/351
sqlalchemy-continuum = "<1.4"

[requires]
python_version = "3.9"

[pipenv]
allow_prereleases = false
